### ISSUE TITLE
Further positions timestamp issue

### ISSUE THREAD

**Issue by cynanrhodes** [rviney/ig_markets#3]
Thanks for your extremely fast response to the previous issue.

Using your updated gem, I now get the following when requesting the Positions method (or the single Position method) 

ArgumentError: Unknown attribute: IGMarkets::Position#created_date_utc, value: "2015-07-24T09:12:37"
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/model.rb:18:in `block in initialize'
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/model.rb:14:in `map'
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/model.rb:14:in `initialize'
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/dealing_platform.rb:65:in `new'
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/dealing_platform.rb:65:in `block in positions'
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/dealing_platform.rb:64:in `map'
	from /Users/User/.rvm/gems/ruby-2.2.2/bundler/gems/ig_markets-f4cd575febe2/lib/ig_markets/dealing_platform.rb:64:in `positions'

thanks

**Comment by cynanrhodes** [comment]
Thanks for your help. Super fast and both methods are working as expected.
