### ISSUE TITLE
transaction#period: failed parsing time

### ISSUE THREAD

**Issue by cynanrhodes** [rviney/ig_markets#5]
Thanks for your recent updates.

In following the docs re the account transactions calls i.e.
ig.account.transactions from: Date.today - 7
ig.account.transactions from: Date.today - 14, to: Date.today - 7

If the period has a value eg. Jun-16 then the below is encountered. If the value is null, then no error occurs.
ArgumentError: IGMarkets::Transaction#period: failed parsing time: JUN-16+0000
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/model/typecasters.rb:90:in `rescue in parse_time_from_string'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/model/typecasters.rb:87:in `parse_time_from_string'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/model/typecasters.rb:73:in `typecaster_time'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/model.rb:150:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/model.rb:150:in `block in define_attribute_writer'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:141:in `block (2 levels) in instantiate_model_from_attributes_hash'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:137:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:137:in `block in instantiate_model_from_attributes_hash'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:134:in `tap'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:134:in `instantiate_model_from_attributes_hash'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:123:in `instantiate_models'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:119:in `block in instantiate_models'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:119:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform.rb:119:in `instantiate_models'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform/account_methods.rb:62:in `history_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ig_markets-0.11/lib/ig_markets/dealing_platform/account_methods.rb:71:in `block in history_request_complete'

**Comment by cynanrhodes** [comment]
Thanks for fixing so quickly. All works at this end.
